### ISSUE TITLE
[Feature Request]Toggles for enabling/disabling Entrust manager globally

### ISSUE THREAD

**Issue by DonSmashio** [PunishXIV/AutoRetainer#101]
Use cases and issues:

Entrust manager is set up. User pulls out a lot of ingredients for crafting. Retainers finish their route and user pulls another item for crafting but all items are now being entrusted. User now has to pull all the items again.

When Entrusts manager lists are setup, especially with a lot of different lists and retainers, preventing retainers from entrusting would require editing the individual lists or removing them from retainers. A user cannot craft for long sessions this way because the ingredients, if they are in the lists, would be pulled back into the retainer.

I'd like to suggest one of two toggles:

1. A checkmark in the main window next to "Enable Autoretainer" and "Multi". Toggling it off will disable the Entrust manager entirely. This way a user can do their thing and then turn it back on.
2. An option in settings that disables Entrust manager when the user is currently using any crafting class. Example [ ] Globally disable Entrust manager while character is a crafting class. Maybe also have the option for gathering class.

**Comment by Limiana** [comment]
Added in testing version but in configuration section for now

**Comment by Limiana** [comment]
Additionally implemented via command: `/ays set EnableEntrustManager false` and `/ays set EnableEntrustManager true`
I think this should be enough
