### ISSUE TITLE
Planner / Assign + Reassign not working

### ISSUE THREAD

**Issue by Fleyrion** [PunishXIV/AutoRetainer#15]
Just hangs at the selection screen for Quick Venture / Hunt / Field Exploration until it errors out.
I'm on the german client btw.
![image](https://user-images.githubusercontent.com/129000857/230630409-9a2b125e-b127-430e-a733-b6e1b4590917.png)

**Comment by Limiana** [comment]
Hello, this should be fixed in testing version of AutoRetainer, please check it and reopen if necessary
