### ISSUE TITLE
Characters are excluded from retainer multimode when encountering an issue with submersibles

### ISSUE THREAD

**Issue by plottingCreeper** [PunishXIV/AutoRetainer#48]
https://discord.com/channels/1001823907193552978/1001825038598676530/1167073797950668812
https://discord.com/channels/1001823907193552978/1001825038598676530/1167201232264380426

If a submersible captain is logged out anywhere other than the correct FC house, AutoRetainer does not handle this in a reasonable way. The character is excluded from _retainer_ multimode, even if it's near a summoning bell. The character is not excluded from captain multimode. 
Multimode is then disabled entirely, stopping all plugin operation. A more sensible behaviour would be for the captain to be excluded from captain multimode, and for plugin operation to continue.

**Comment by Limiana** [comment]
Should no longer have anything like that
