### ISSUE TITLE
CN version

### ISSUE THREAD

**Issue by SakuraSayaka** [PunishXIV/AutoRetainer#64]
Multi-Mode crashes on CN clients

**Comment by Kooord** [comment]
Multi-Mode crashes on CN clients，Can you help me？

**Comment by Limiana** [comment]
Hello!
The answer is - maybe. I've got my hands on CN client and investigating the issue

**Comment by Kooord** [comment]
Thanks！

**Comment by Limiana** [comment]
You can get CN version from this repo: `https://github.com/NightmareXIV/MyDalamudPlugins/raw/main/cn.json`
I can't guarantee that all functions are working, but base ones should
