### ISSUE TITLE
CN server

### ISSUE THREAD

**Issue by seraphim424** [PunishXIV/AutoRetainer#67]
Multi Mode unable to log in to role on Doudouchai server

**Comment by Limiana** [comment]
hey, have you tried specifically CN version? https://github.com/PunishXIV/AutoRetainer/issues/64

**Comment by seraphim424** [comment]
yes,   https://github.com/NightmareXIV/MyDalamudPlugins/raw/main/cn.json  .
but ,only Doudouchai server ﻿cannot automatically log in to the role .
The other three game regions can.

**Comment by seraphim424** [comment]
Previously, an author has modified multi  . https://github.com/Nesb01t/AutoRetainerNative  .
But he doesn't update anymore .

The official version also has the same issue ,only Doudouchai server ﻿cannot automatically log in to the role .

**Comment by Limiana** [comment]
All AR CN issues should be resolved in a version available here: https://github.com/NightmareXIV/MyDalamudPlugins/blob/main/cn.json
