### ISSUE TITLE
FC Statistics breaks if you don't have Venture Statistics enabled

### ISSUE THREAD

**Issue by Ferikisekai** [PunishXIV/AutoRetainer#71]
Without Venture Statistics enabled, FC Data shows the Gil Statistics instead, and you can't check FC points.

I'm using the Testing version.

**Comment by A1one-020** [comment]
how to enable the venture statistics? and i cannot use auto expert delivery either... ways to download previous version pack?

**Comment by Limiana** [comment]
> how to enable the venture statistics? and i cannot use auto expert delivery either... ways to download previous version pack?

type "statistic" into setting search and the option will be highlighted
as for expert delivery, type `/xlbranch` and switch to release
also the bug is now fixed
