### ISSUE TITLE
Cant turn off Autoretainer

### ISSUE THREAD

**Issue by zinc69** [PunishXIV/AutoRetainer#75]
if i deselect the "Enable AutoRetainer" and open summoning bell again the box reappears. 4.3.0.9

**Comment by Sabin-DC** [comment]
Just adding my 2 cents that this happens to me aswell. I have to disable in dalamud to not have it instantly refresh my retainers

**Comment by porisius** [comment]
Check these settings... (Expert Mode Required, I think...)

![image](https://github.com/PunishXIV/AutoRetainer/assets/47161774/ca14270c-c204-45b0-9327-8dcbdf25cd94)

**Comment by amaraame** [comment]
> Check these settings... (Expert Mode Required)
> 
how do you get expert mode?

**Comment by Limiana** [comment]
`/ays expert` to enable expert mode section
