### ISSUE TITLE
AutoRetainer 4.3.1.0 - Wait on Login screen not working

### ISSUE THREAD

**Issue by throwawayusername-2024** [PunishXIV/AutoRetainer#76]
On multi-mode / night mode, I have the "wait on login screen" option selected so that I won't be hit by the AFK timer. Except this is still happening anyways.

I think the plugin is actually getting stuck on the "logout and return to the title screen" prompt after my last character is finished. Then this eventually gets AFK kicked and the plugin stops functioning.

**Comment by Limiana** [comment]
Hello! I'm currently investigating this issue, I will report when I have more information or solution

**Comment by Limiana** [comment]
Should not be an issue anymore
