### ISSUE TITLE
[Bug] [7.01] [v4.3.1.6] Retainers randomly not working since last night

### ISSUE THREAD

**Issue by Polarthief** [PunishXIV/AutoRetainer#80]
> [7/18/2024 8:55:46 AM -04:00] Task WaitForYesAlreadyDisabledTask took too long to execute
   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\VS\AutoRetainer\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 158

This isn't because of the weird update to retainers that SE pushed (at least i don't think it is since it's been working fine all of Tuesday and most of Wednesday); randomly last night, collecting ventures is simply not working. It will try the first retainer then completely hang on the menu of that one. If I force it along manually, it will just hang on the second. In addition, turning on Multi Mode doesn't seem to trigger trying to go for retainers at all when it previously would.

A friend mentioned when they turned off "auto entrust duplicates" that it worked for them, but I never turned mine on to begin with. I also have no planner either, just routine Assign + Reassign. I did not mess with any settings for this to break either. I did add some (unrelated) plugins, but after disabling all the ones I had enabled, it's still not working.

**Comment by Phenrei** [comment]
It appears a client struct was changed in Dalamud which broke a few things for me all at the same time related to timers on the login screen, this plugin included. The console is full of error messages like this from AutoRetainer:

```
Exception during raise of "Void <InvokeSafely>b__0()"
	System.MissingFieldException: Field not found: 'FFXIVClientStructs.FFXIV.Client.UI.Agent.AgentLobby.IdleTime'.
	   at AutoRetainer.Modules.Multi.MultiMode.Tick()
	   at AutoRetainer.AutoRetainer.Tick(Object _) in D:\VS\AutoRetainer\AutoRetainer\AutoRetainer.cs:line 430
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

**Comment by Polarthief** [comment]
Just got another hang-up on the GC Turn-in feature. It usually exits the NPC's menu completely when you're out of items/capped on seals and it doesn't want to overcap you, but instead it just, didn't exit the menu.

![image](https://github.com/user-attachments/assets/0621ce6c-0401-4c88-ae48-076386f8fc3f)

Seems to be the exact same issue, regarding line 158 of TaskManager.cs (note: I don't know programming at all, lol).

**Comment by Polarthief** [comment]
Thank you for the update! Working as of v4.3.1.7!
