### ISSUE TITLE
Allowing to comfirm the "Your retainer will be unable to process item buyback..." dialog for CN and ZH clients

### ISSUE THREAD

**Issue by kengao** [PunishXIV/AutoRetainer#89]
Hello, I am providing the Chinese text for "Your retainer will be unable to process item buyback requests once recalled. Are you sure you wish to proceed?" located in [Lang.cs ]( https://github.com/PunishXIV/AutoRetainer/blob/c766f7010add7a9dd97328c7e05ad3a108e06700/AutoRetainer/Lang.cs#L257 ), hope this allows the addon to comfirm that dialog.  (Sorry I am not familiar with PR, hope this way works.)
They are

"让雇员返回后将无法购回委托卖掉的道具，
确定要继续吗？", 
"讓僱員返回後將無法購回委託賣掉的道具，
確定要繼續嗎？"

The newline after '，' were shown in the UI, not sure if they need to be kept in code. 

Thanks!

**Comment by Limiana** [comment]
Thank you! Will be added in next version

**Comment by Limiana** [comment]
Added in testing version
