### ISSUE TITLE
[Suggestion] Item Management

### ISSUE THREAD

**Issue by Nivyan** [PunishXIV/AutoRetainer#93]
**Example**
1) Specify a retainer to store all faded Orchestration items.
2) When depositing/withdrawing items, check player inventory for all faded Orchestration items and deposit them.

**Reasoning**
For some types of items, this would be incredibly useful - things like dyes, faded orchestration items, raid-specific items, coffers, materia etc. These items take up space in your inventory, and have no reason to be carried until needed.

**Suggested implementation**
Initially, simply using the types specified on the Marketboard would be sufficient for a ton of items.

**Comment by Limiana** [comment]
Added in testing version
