### ISSUE TITLE
Autoretainer opens retainer inventory instead of going back to retainer list

### ISSUE THREAD

**Issue by MikevLeeuwen** [PunishXIV/AutoRetainer#94]
When having autoretainer open, as of today it seems to be going to the retainer inventory after each retainer instead of going back to the retainer-list. This causes the loop to break and only one retainer to be sent on a new mission.

I do not have multi mode enabled, only auto retainer. For all retainers the entrust items option is disabled, as is the option to withdraw/deposit gil.
![retainer options](https://github.com/user-attachments/assets/b2a829a9-a70b-459c-a92a-3f23ae3413cd)

My fps is capped at 60 fps, and always is around that cap, nowhere near the 20 or lower for this to be an issue. 
I did increase the interaction delay from 8 to 20 to see if this would fix the issue, which it didn't.

Autoretainer version: 4.3.2.9 (Testing version)

If you require any more information for this issue, please don't hesitate to ask!

**Comment by Limiana** [comment]
This issue should be fixed in 4.3.3.0
