### ISSUE TITLE
FEATURE REQUEST: Entrust Plan

### ISSUE THREAD

**Issue by Wolfies11681** [PunishXIV/AutoRetainer#96]
With the option to create multiple plans, I would like the ability to name each Entrust Plan. Would be much easier to organize my plans and assign them properly.

**Comment by Taurenkey** [comment]
You can already rename them, it's the textbox under the dropdown in the manager.

**Comment by Wolfies11681** [comment]
Ah, Damit! Didn't think to click that. When I delete it all it then shows, Plan Name. Sigh...

Closing Ticket.
