### ISSUE TITLE
[Request] Add Ability to Filter Login Menu by Service Accounts

### ISSUE THREAD

**Issue by VeraNala** [PunishXIV/AutoRetainer#97]
Hello I'd like to request the ability to either filter / sort this character login menu by assigned Service Account, or perhaps even have tabs / some form of pagination for switching between lists of characters per assigned Service Account.
![ffxiv_dx11_geCPhtFgCO](https://github.com/user-attachments/assets/19a93703-c8c3-4a30-ba4b-5515135a98e6)
Thanks!

**Comment by Limiana** [comment]
Added in testing version
