### ISSUE TITLE
[Feature Request] Exclude items on Protection List from Entrust Manager.

### ISSUE THREAD

**Issue by Rakmarok** [PunishXIV/AutoRetainer#99]
![image](https://github.com/user-attachments/assets/8bcd7b3d-5e0a-43c3-8896-c703c19bed48)

I want these items above in my inventory permanently, but they belong to categories that I set to be entrusted to one of my retainers, causing them to be entrusted even though they are on the protection list (as you can see below).

![image](https://github.com/user-attachments/assets/657f51c1-ea68-49fe-bbc9-4d67b656db2f)

The entrust manager honouring the protection list would be a huge QoL improvement. Thank you.

**Comment by Limiana** [comment]
Added in testing version
